### ISSUE TITLE
Can't able to show my code pen!!

### ISSUE THREAD

**Issue by Akki-Rawat** [Jay-study-nildana/NodeJSForStudents#4]
Hello Jay sir 

Sir as you told me in today's class to share my  code in the code pen , Sir I tried to share my code but my code contains two html files in it and I'm not able to find a way for merging those two files in code pen. What should I do sir? I checked in the internet also but still i was not able to do it. Please help me out in this issue sir...
Thank You 

Akshat

**Comment by Jay-study-nildana** [comment]
@Akki-Rawat 

Option 1 : Then, put your code in github repo, and share the github link here. make it public, of course :) 

Option 2 : Try code sandbox. 

Note: CodePen does not support multiple files. 

Jay

**Comment by Akki-Rawat** [comment]
> @Akki-Rawat
> 
> Option 1 : Then, put your code in github repo, and share the github link here. make it public, of course :)
> 
> Option 2 : Try code sandbox.
> 
> Note: CodePen does not support multiple files.
> 
> Jay

Okay sir i made the repo alrdy.

Thanks for your guidance sir

**Comment by Jay-study-nildana** [comment]
@Akki-Rawat 

sounds good. 

Yes, code sandbox is definitely better if you are looking to use multiple files. 

Also, I have a student group community. if you want to, please join. https://discord.gg/CVugpJRBTB

Thanks.

Jay.
