### ISSUE TITLE
How to solve this error ?

### ISSUE THREAD

**Issue by asmallick1999** [Jay-study-nildana/NodeJSForStudents#5]
![image](https://user-images.githubusercontent.com/84728108/224059157-694b89e0-a779-4ecd-b4e1-74e47e97a580.png)

Well I tried to "POST" data using React + Express + MongoDB 
and fetched the data using "GET" method 
I can get the data on the console, but I got this 👆🏻 error when I was trying to show it on my page (HomePage Component)

I am adding my repo so that you can get the code : https://github.com/asmallick1999/PostApiPractice

**Comment by Jay-study-nildana** [comment]
@asmallick1999 

I will look into this. will keep you posted.

**Comment by Jay-study-nildana** [comment]
@asmallick1999 

I am unable to run your code. 

1. There is no readme.md file explaining how to run your project. Please add readme.md to both backend and front end project folders. 
1. I was able to run your front end with the command, 'npm start', but, your backend, 'npm run dev' is not there. Also, there is actually nothing in the scripts section of your backend.

So, exactly how are you able to run your backend? It has become a huge mystery for me. 

Let me know once you have updated the readme file with steps on how to run the project on my computer. 

Thanks.

Jay.

**Comment by asmallick1999** [comment]
Sure I will add a readme.md file

Umm I use "supervisor" to run my backend 
like -> supervisor app.js

**Comment by asmallick1999** [comment]
@Jay-study-nildana Sir
I added Readme.md file on the Backend please check :)

**Comment by Jay-study-nildana** [comment]
@asmallick1999 

ah, now, it's easy to follow. Okay, I will check and update. As you know, weekends I have the edureka batches. So, next, I will be able to check the code on Monday only. 

If something is super urgent, let me know by direct messaging me on discord. 

Jay
https://discord.gg/CVugpJRBTB

**Comment by asmallick1999** [comment]
Well, I used nodemon. But I don't know suddenly my nodemon stopped working so I searched for the problems and I didn't get the exact solution till then I started using supervisor

**Comment by asmallick1999** [comment]
@Jay-study-nildana 
Sir, If you downloaded the code please update it "git pull", I changed something on it.

**Comment by asmallick1999** [comment]
After Some research, I got the solution but facing another issue hehe :)

**Comment by Jay-study-nildana** [comment]
@asmallick1999 

This is still not helping. You need to change some settings (not the entire project, just some settings) so that I can run it with the standard rules

```
npm install
npm run dev

```

if you are using some other method, then, I cannot really help you. Check the example projects I have shared with you. Please use that method.

Jay
https://discord.gg/CVugpJRBTB

**Comment by Jay-study-nildana** [comment]
folks,

closing this.

Jay.
