### ISSUE TITLE
Unseen error of node💀

### ISSUE THREAD

**Issue by Akki-Rawat** [Jay-study-nildana/NodeJSForStudents#6]
Hey i added you i n my private repo of node js, cause i'm facing a (Cannot find module './server/MyServer')

And my all files are correct and i give the right path to the server but still i'm facing this error, 
so i need your help to solve this problem of mine.

whenever you got free time please  help me😁

**Link of my private repo**
[https://github.com/Akki-Rawat/Node-JS-Project](url)

Thanks
Akki

**Comment by Jay-study-nildana** [comment]
@Akki-Rawat 

I will investigate this monday. I have got your invite for the private repo. 

will update once I have more. 

as usual, make sure

1. your readme is updated with steps on what I have to do to run the project on my computer. 
1. if possible mention the file name where you are getting error.
1. and, mention the line number, or, better yet, include a code block here on this thread so I know exactly what I am looking for.
1. and of course any screenshots, error messages and other information that can help me replicate the issue on my computer.

Thanks.

Jay.

**Comment by Jay-study-nildana** [comment]
@Akki-Rawat 

I cannot help when readme file is empty. 

![Akki Steps Missing](https://user-images.githubusercontent.com/14297315/235419513-9dbba7b4-b2fe-4c50-a83f-3ea7ce29d888.jpg)

once you have put the readme steps, let me know. 

Thanks

Jay.

**Comment by Akki-Rawat** [comment]
@Jay-study-nildana Sir I updated my readme file and mention the error and its location properly, now you can see the error in my server.

**Comment by Jay-study-nildana** [comment]
@Akki-Rawat 

your readme is still useless. 

check the examples here, 

1. https://github.com/Jay-study-nildana/NodeJSForStudents/tree/main/NodeJSHelloWorld
2. https://github.com/Jay-study-nildana/vercelbackenddemo

main thing, you should explain how to "run the project"

Back end is not like react JS. there are many different ways to run the project. So, if you don't put steps on how to run the project, then, I won't know how to run it. 

Once again, update your readme and let me know. 

And, yes, this is very frustrating, but, you are still learning how to ask questions. Remember what I told you in class. 

"Asking questions itself is a skill. Like every other skill, how to ask questions is also something you learn slowly, over time"

Jay.
