### ISSUE TITLE
Mongo DB issue Everyday_Id

### ISSUE THREAD

**Issue by Jay-study-nildana** [Jay-study-nildana/NodeJSForStudents#8]
@Jay-study-nildana 
Hello sir, 
I'm from ur last edureka batch student. 

I have doubt in mongodb and react please help me sir. 
This my live api link : https://myallbirsapp.onrender.com/product

In this I need to fetch only Everyday_Id details where it all present but I'm not able to get. 
I'm getting all data othere wise Im getting only one Everyday_Id day which I got using params. 

Please sir help me..... 
I'm really trying hard please....

_Originally posted by @Gagana30 in https://github.com/Jay-study-nildana/TutoringTrainingStudents/discussions/102#discussioncomment-6290088_

**Comment by Jay-study-nildana** [comment]
@Gagana30 

Live app link will not help me. For me to help, you need to, share the full project code, via github. 

Please see this link, 

https://github.com/Jay-study-nildana/FrontEndForStudents/discussions/25

it will show how you should ask questions. That is the format you have to follow to take help. As usual, you have more doubts, let me know.

and of course, you are free to connect with me on discord and directly chat with me, and also have video zoom calls with me, no problem.

Happy coding. 

Jay (Vijayasimha BR)
Coding Tutor. Career and Life Coach
----
Discord: Jay_HisManyHobbies#6392

**Comment by Gagana30** [comment]
> @Gagana30
> 
> Live app link will not help me. For me to help, you need to, share the full project code, via github.
> 
> Please see this link,
> 
> [Jay-study-nildana/FrontEndForStudents#25](https://github.com/Jay-study-nildana/FrontEndForStudents/discussions/25)
> 
> it will show how you should ask questions. That is the format you have to follow to take help. As usual, you have more doubts, let me know.
> 
> and of course, you are free to connect with me on discord and directly chat with me, and also have video zoom calls with me, no problem.
> 
> Happy coding.
> 
> Jay (Vijayasimha BR) Coding Tutor. Career and Life Coach Discord: Jay_HisManyHobbies#6392

Thank u sir for ur reply which gives me hopes to do more things better and learn more

**Comment by Jay-study-nildana** [comment]
@Gagana30 

no problem. keep me posted.

Jay (Vijayasimha BR)
Coding Tutor. Career and Life Coach
Discord: Jay_HisManyHobbies#6392
